### ISSUE TITLE
Patch 1.0.4 with 0.5 increment sliders

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-black-box-study#28]
If Shima continues with 1.0.4, @kathy-phet suggested adding the 0.5 increment sliders.  Assigned to @arouinfar to keep an eye on this and see if it becomes necessary (if we aren't proceeding with the 1.0.7+ line).

**Comment by arouinfar** [comment]
@samreid this would be the version we should use for #29.

**Comment by samreid** [comment]
For #29 I was planning to publish only the explore screen.  Hence I would need to publish two versions, one with the explore screen and one without.

**Comment by samreid** [comment]
@arouinfar #29 is underway and using different branches.  6 days ago it seemed unclear whether Shima would proceed with 1.0.4 or 1.0.7+.  Can you comment?

**Comment by arouinfar** [comment]
@samreid Shima has a few studies going on. She has already collected pre-test/pre-semester data and conducted some individual interviews with Stanford students. Shima also has a high school classroom study coming up next month. 

For the Stanford population, the version without wire stubs (1.0.4) was acceptable, though not ideal. The problems with the voltmeter in #27 made the 1.0.7 unacceptable for use with students because it could potentially interfere with how students interacted with the sim. 

For the upcoming high school study, the wire stubs are absolutely necessary, so we'll need to proceed with the change requests in #30 and possibly #31 and publish a version 1.0.8 (or higher).

**Comment by samreid** [comment]
@arouinfar thanks for the clarification.  I'll close this issue and continue on #27, #30 and possibly #31 for 1.0.8+

**Comment by samreid** [comment]
And #6 it looks like.
